# name: Waka Readme

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '05 0 * * *'

# jobs:
#   update-readme:
#     name: Update this repo's README
#     runs-on: ubuntu-latest
#     steps:
#       - uses: ApoorvTyagi/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           SHOW_PROJECTS: "False"
#           SHOW_LINES_OF_CODE: "False" 
#           SHOW_LANGUAGE: "False"
#           SHOW_OS: "False"
#           SHOW_EDITORS: "False"
#           SHOW_TIMEZONE: "False"
#           SHOW_LOC_CHART: "False"
#           SHOW_PROFILE_VIEWS: "False"
#           SHOW_SHORT_INFO: "False"

name: Waka Readme

on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: miermontoto/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True" 
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LOC_CHART: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"